# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  Image_Name: 'csharp_image'
  registry_Name: 'imageregistry4461.azurecr.io'
  acrName: 'akhil4461'
  containerapp: 'backendapp'
  resource_Group: 'Devops_training'
  Container_App_env: 'managedEnvironment-Devopstraining-a55b'


resources:
- repo: self

stages:
  - stage: Build
    jobs:
      - job: BuildandPush
        steps:        
        - task: Docker@0
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureSubscription: 'Pay-As-You-Go(5083e524-6907-48df-8508-9fa606d81016)'
            azureContainerRegistry: '{"loginServer":"akhil4461.azurecr.io", "id" : "/subscriptions/5083e524-6907-48df-8508-9fa606d81016/resourceGroups/Devops_training/providers/Microsoft.ContainerRegistry/registries/akhil4461"}'
            action: 'Build an image'
            dockerFile: '$(Build.SourcesDirectory)/backend_api/backend_api_csharp/Dockerfile'
            imageName: '$(Image_Name):$(Build.BuildId)'
        
        - task: Docker@0
          inputs:
            containerregistrytype: 'Azure Container Registry'
            azureSubscription: 'Pay-As-You-Go(5083e524-6907-48df-8508-9fa606d81016)'
            azureContainerRegistry: '{"loginServer":"akhil4461.azurecr.io", "id" : "/subscriptions/5083e524-6907-48df-8508-9fa606d81016/resourceGroups/Devops_training/providers/Microsoft.ContainerRegistry/registries/akhil4461"}'
            action: 'Push an image'
            imageName: '$(Image_Name):$(Build.BuildId)'
        
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - task: AzureContainerApps@1
        inputs:
          azureSubscription: 'Pay-As-You-Go(5083e524-6907-48df-8508-9fa606d81016)'
          acrName: '$(acrName)'
          acrUsername: '$(acr_username)'
          acrPassword: '$(acr_password)'
          imageToDeploy: 'akhil4461.azurecr.io/$(Image_Name):$(Build.BuildId)'
          containerAppName: '$(containerapp)'
          resourceGroup: '$(resource_Group)'
          containerAppEnvironment: '$(Container_App_env)'
          targetPort: '3500'
          ingress: 'external'