# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  Image_Name: 'csharp_image'
  registry_Name: 'imageregistry4461.azurecr.io'

resources:
- repo: self

stages:
  - stage: Build
    jobs:
      - job: BuildandPush
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker'
            repository: 'akhil4461 / backendapp'
            command: 'buildAndPush'
            Dockerfile: '$(Build.SourcesDirectory)/backend_api/backend_api_csharp/Dockerfile'
      
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - task: AzureContainerApps@1
        inputs:
          azureSubscription: 'Pay-As-You-Go(5083e524-6907-48df-8508-9fa606d81016)'
          acrName: 'akhil4461'
          acrUsername: 'akhil4461'
          acrPassword: 'House@4461'
          imageToDeploy: 'akhil4461/backendapp'
          containerAppName: 'infycapp-01'
          resourceGroup: 'Devops_training'
          containerAppEnvironment: 'managedEnvironment-Devopstraining-8ff7'
          targetPort: '3500'
          ingress: 'external'
